
//This code generated by tool. Do not hand update!
//ALSO DO NOT DELETE OR YOU WILL LOOSE YOUR FORM!
namespace uAssist.EditorDesigner
{
    using UnityEngine;
    using UnityEditor;
    using System.Collections;
    using System.Collections.Generic;
    using uAssist.UEditorWidgets;
    using uAssist.UEditorWidgets.Internal;
    using uAssist.Forms;

    [UWidgetForm]
    public partial class frmOpenDesigner : frmBase
    {



        //Widget declarations
		private UEditorWidgetLabel LabelControl = UWidget.Create<UEditorWidgetLabel>();
		private UEditorWidgetButton _btnOpenForm = UWidget.Create<UEditorWidgetButton>();
		private UEditorWidgetButton _btnCancel = UWidget.Create<UEditorWidgetButton>();
		private UEditorPanelArea AreaPanel = UWidget.Create<UEditorPanelArea>();
		private UEditorPanelVertical ScrollFrame = UWidget.Create<UEditorPanelVertical>();
		private UEditorPanelScroll _formsList = UWidget.Create<UEditorPanelScroll>();


        public override void InitalizeComponents()
        {

        //Form settings
		this.name = "frmOpenDesigner";
		this.FormTitle = "Open Form";
		this.MaxHeight = 250;
		this.MaxWidth = 400;
		this.DesignerDropOverridePath = @"Assets\uAssist\EditorDesigner\Editor\";
		this.DesignerNameSpace = @"uAssist.EditorDesigner";
		this.AutoMenuOption = true;

            
        //Property settings
		//Property setters for ->LabelControl
		this.LabelControl.Label = "Select a form to open";
		this.LabelControl.FontSize = 22;
		this.LabelControl.FontStyle = UnityEngine.FontStyle.BoldAndItalic;
		this.LabelControl.WordWrap = false;
		this.LabelControl.Alignment = UnityEngine.TextAnchor.UpperLeft;
		this.LabelControl.BaseStyle = "";
		this.LabelControl.Clipping = UnityEngine.TextClipping.Overflow;
		this.LabelControl.Margin.top = 2;
		this.LabelControl.Margin.bottom = 2;
		this.LabelControl.Margin.left = 4;
		this.LabelControl.Margin.right = 4;
		this.LabelControl.Padding.top = 5;
		this.LabelControl.Padding.bottom = 2;
		this.LabelControl.Padding.left = 3;
		this.LabelControl.Padding.right = 3;
		this.LabelControl.Border.top = 0;
		this.LabelControl.Border.bottom = 0;
		this.LabelControl.Border.left = 0;
		this.LabelControl.Border.right = 0;
		this.LabelControl.Height = 16f;
		this.LabelControl.Width = 100f;
		this.LabelControl.Name = "LabelControl";
		this.LabelControl.PositionX = 1f;
		this.LabelControl.PositionY = 1f;
		this.LabelControl.GUIEnabled = true;
		this.LabelControl.WidgetShouldRender = true;
		this.LabelControl.LayoutExpandHeight = false;
		this.LabelControl.LayoutExpandWidth = false;
		this.LabelControl.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.WindowSpace;
		this.AddChild(this.LabelControl, true);
	
	
		//Property setters for ->_btnOpenForm
		this._btnOpenForm.Label = "Open Form";
		this._btnOpenForm.FontSize = 11;
		this._btnOpenForm.FontStyle = UnityEngine.FontStyle.Normal;
		this._btnOpenForm.WordWrap = false;
		this._btnOpenForm.Alignment = UnityEngine.TextAnchor.MiddleCenter;
		this._btnOpenForm.BaseStyle = "";
		this._btnOpenForm.Clipping = UnityEngine.TextClipping.Overflow;
		this._btnOpenForm.Margin.top = 2;
		this._btnOpenForm.Margin.bottom = 2;
		this._btnOpenForm.Margin.left = 4;
		this._btnOpenForm.Margin.right = 4;
		this._btnOpenForm.Padding.top = 1;
		this._btnOpenForm.Padding.bottom = 2;
		this._btnOpenForm.Padding.left = 3;
		this._btnOpenForm.Padding.right = 3;
		this._btnOpenForm.Border.top = 4;
		this._btnOpenForm.Border.bottom = 4;
		this._btnOpenForm.Border.left = 6;
		this._btnOpenForm.Border.right = 6;
		this._btnOpenForm.Height = 20f;
		this._btnOpenForm.Width = 100f;
		this._btnOpenForm.Name = "_btnOpenForm";
		this._btnOpenForm.PositionX = 270f;
		this._btnOpenForm.PositionY = 210f;
		this._btnOpenForm.GUIEnabled = false;
		this._btnOpenForm.WidgetShouldRender = true;
		this._btnOpenForm.LayoutExpandHeight = false;
		this._btnOpenForm.LayoutExpandWidth = false;
		this._btnOpenForm.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.WindowSpace;
		this.AddChild(this._btnOpenForm, true);
	
	
		//Property setters for ->_btnCancel
		this._btnCancel.Label = "Cancel";
		this._btnCancel.FontSize = 11;
		this._btnCancel.FontStyle = UnityEngine.FontStyle.Normal;
		this._btnCancel.WordWrap = false;
		this._btnCancel.Alignment = UnityEngine.TextAnchor.MiddleCenter;
		this._btnCancel.BaseStyle = "";
		this._btnCancel.Clipping = UnityEngine.TextClipping.Overflow;
		this._btnCancel.Margin.top = 2;
		this._btnCancel.Margin.bottom = 2;
		this._btnCancel.Margin.left = 4;
		this._btnCancel.Margin.right = 4;
		this._btnCancel.Padding.top = 1;
		this._btnCancel.Padding.bottom = 2;
		this._btnCancel.Padding.left = 3;
		this._btnCancel.Padding.right = 3;
		this._btnCancel.Border.top = 4;
		this._btnCancel.Border.bottom = 4;
		this._btnCancel.Border.left = 6;
		this._btnCancel.Border.right = 6;
		this._btnCancel.Height = 20f;
		this._btnCancel.Width = 100f;
		this._btnCancel.Name = "_btnCancel";
		this._btnCancel.PositionX = 160f;
		this._btnCancel.PositionY = 210f;
		this._btnCancel.GUIEnabled = false;
		this._btnCancel.WidgetShouldRender = true;
		this._btnCancel.LayoutExpandHeight = false;
		this._btnCancel.LayoutExpandWidth = false;
		this._btnCancel.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.WindowSpace;
		this.AddChild(this._btnCancel, true);
	
	
		//Property setters for ->AreaPanel
		this.AreaPanel.BaseStyle = "";
		this.AreaPanel.Clipping = UnityEngine.TextClipping.Overflow;
		this.AreaPanel.Margin.top = 0;
		this.AreaPanel.Margin.bottom = 0;
		this.AreaPanel.Margin.left = 0;
		this.AreaPanel.Margin.right = 0;
		this.AreaPanel.Padding.top = 0;
		this.AreaPanel.Padding.bottom = 0;
		this.AreaPanel.Padding.left = 0;
		this.AreaPanel.Padding.right = 0;
		this.AreaPanel.Border.top = 0;
		this.AreaPanel.Border.bottom = 0;
		this.AreaPanel.Border.left = 0;
		this.AreaPanel.Border.right = 0;
		this.AreaPanel.Height = 150f;
		this.AreaPanel.Width = 320f;
		this.AreaPanel.Name = "AreaPanel";
		this.AreaPanel.ChildrenShouldRender = true;
		this.AreaPanel.PositionX = 40f;
		this.AreaPanel.PositionY = 45f;
		this.AreaPanel.GUIEnabled = true;
		this.AreaPanel.WidgetShouldRender = true;
		this.AreaPanel.LayoutExpandHeight = false;
		this.AreaPanel.LayoutExpandWidth = false;
		this.AreaPanel.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.WindowSpace;
		this.AddChild(this.AreaPanel, true);
	
	
		//Property setters for ->ScrollFrame
		this.ScrollFrame.BaseStyle = "";
		this.ScrollFrame.Clipping = UnityEngine.TextClipping.Overflow;
		this.ScrollFrame.Margin.top = 0;
		this.ScrollFrame.Margin.bottom = 0;
		this.ScrollFrame.Margin.left = 0;
		this.ScrollFrame.Margin.right = 0;
		this.ScrollFrame.Padding.top = 0;
		this.ScrollFrame.Padding.bottom = 0;
		this.ScrollFrame.Padding.left = 0;
		this.ScrollFrame.Padding.right = 0;
		this.ScrollFrame.Border.top = 0;
		this.ScrollFrame.Border.bottom = 0;
		this.ScrollFrame.Border.left = 0;
		this.ScrollFrame.Border.right = 0;
		this.ScrollFrame.Height = 150f;
		this.ScrollFrame.Width = 310f;
		this.ScrollFrame.Name = "ScrollFrame";
		this.ScrollFrame.ChildrenShouldRender = true;
		this.ScrollFrame.PositionX = 40f;
		this.ScrollFrame.PositionY = 45f;
		this.ScrollFrame.GUIEnabled = true;
		this.ScrollFrame.WidgetShouldRender = true;
		this.ScrollFrame.LayoutExpandHeight = false;
		this.ScrollFrame.LayoutExpandWidth = false;
		this.ScrollFrame.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.Layout;
		this.AreaPanel.AddChild(this.ScrollFrame);
	
	
		//Property setters for ->_formsList
		this._formsList.BaseStyle = "textField";
		this._formsList.Clipping = UnityEngine.TextClipping.Overflow;
		this._formsList.Margin.top = 0;
		this._formsList.Margin.bottom = 0;
		this._formsList.Margin.left = 0;
		this._formsList.Margin.right = 0;
		this._formsList.Padding.top = 0;
		this._formsList.Padding.bottom = 0;
		this._formsList.Padding.left = 0;
		this._formsList.Padding.right = 0;
		this._formsList.Border.top = 3;
		this._formsList.Border.bottom = 3;
		this._formsList.Border.left = 3;
		this._formsList.Border.right = 3;
		this._formsList.Height = -1f;
		this._formsList.Width = 300f;
		this._formsList.Name = "_formsList";
		this._formsList.ChildrenShouldRender = true;
		this._formsList.PositionX = 1f;
		this._formsList.PositionY = 1f;
		this._formsList.GUIEnabled = true;
		this._formsList.WidgetShouldRender = true;
		this._formsList.LayoutExpandHeight = false;
		this._formsList.LayoutExpandWidth = false;
		this._formsList.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.Layout;
		this.ScrollFrame.AddChild(this._formsList);
	
	


        }

    }
}