
//This code generated by tool. Do not hand update!
//ALSO DO NOT DELETE OR YOU WILL LOOSE YOUR FORM!
namespace uAssist.EditorDesigner
{
    using UnityEngine;
    using UnityEditor;
    using System.Collections;
    using System.Collections.Generic;
    using uAssist.UEditorWidgets;
    
    public partial class UControlDesignerTools : UEditorWidgetBase
    {

        //Widget declarations
        private UEditorPanelVertical _scrollWindow = UWidget.Create<UEditorPanelVertical>();
        private UEditorPanelScroll _toolsScroll = UWidget.Create<UEditorPanelScroll>();
        private UEditorWidgetButton _btnPanels = UWidget.Create<UEditorWidgetButton>();
        private UEditorPanelVertical _vertPanels = UWidget.Create<UEditorPanelVertical>();
        private UEditorWidgetButton _btnWidgets = UWidget.Create<UEditorWidgetButton>();
        private UEditorPanelVertical _vertWidgets = UWidget.Create<UEditorPanelVertical>();
        private UEditorWidgetButton _btnControls = UWidget.Create<UEditorWidgetButton>();
        private UEditorPanelVertical _vertControls = UWidget.Create<UEditorPanelVertical>();
        private UEditorWidgetButton _btnDecorators = UWidget.Create<UEditorWidgetButton>();
        private UEditorPanelVertical _vertDecorators = UWidget.Create<UEditorPanelVertical>();
        private UEditorWidgetButton _btnOthers = UWidget.Create<UEditorWidgetButton>();
        private UEditorPanelVertical _vertOthers = UWidget.Create<UEditorPanelVertical>();


        public void InitalizeComponents()
        {

        //Form settings
		this.name = "UControlDesignerTools";
            
        //Property settings
		//Property setters for ->_scrollWindow
		this._scrollWindow.BaseStyle = "textField";
		this._scrollWindow.Clipping = UnityEngine.TextClipping.Clip;
		this._scrollWindow.Margin.top = 0;
		this._scrollWindow.Margin.bottom = 0;
		this._scrollWindow.Margin.left = 0;
		this._scrollWindow.Margin.right = 0;
		this._scrollWindow.Padding.top = 0;
		this._scrollWindow.Padding.bottom = 0;
		this._scrollWindow.Padding.left = 0;
		this._scrollWindow.Padding.right = 0;
		this._scrollWindow.Border.top = 3;
		this._scrollWindow.Border.bottom = 3;
		this._scrollWindow.Border.left = 3;
		this._scrollWindow.Border.right = 3;
		this._scrollWindow.Height = 400f;
		this._scrollWindow.Width = 120f;
		this._scrollWindow.Name = "_scrollWindow";
		this._scrollWindow.ChildrenShouldRender = true;
		this._scrollWindow.PositionX = 0f;
		this._scrollWindow.PositionY = 0f;
		this._scrollWindow.GUIEnabled = true;
		this._scrollWindow.WidgetShouldRender = true;
		this._scrollWindow.LayoutExpandHeight = false;
		this._scrollWindow.LayoutExpandWidth = false;
		this._scrollWindow.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.Layout;
	
		//Property setters for ->_toolsScroll
		this._toolsScroll.BaseStyle = "";
		this._toolsScroll.Clipping = UnityEngine.TextClipping.Clip;
		this._toolsScroll.Margin.top = 0;
		this._toolsScroll.Margin.bottom = 0;
		this._toolsScroll.Margin.left = 0;
		this._toolsScroll.Margin.right = 0;
		this._toolsScroll.Padding.top = 0;
		this._toolsScroll.Padding.bottom = 0;
		this._toolsScroll.Padding.left = 0;
		this._toolsScroll.Padding.right = 0;
		this._toolsScroll.Border.top = 0;
		this._toolsScroll.Border.bottom = 0;
		this._toolsScroll.Border.left = 0;
		this._toolsScroll.Border.right = 0;
		this._toolsScroll.Height = -1f;
		this._toolsScroll.Width = -1f;
		this._toolsScroll.Name = "_toolsScroll";
		this._toolsScroll.ChildrenShouldRender = true;
		this._toolsScroll.PositionX = 1f;
		this._toolsScroll.PositionY = 1f;
		this._toolsScroll.GUIEnabled = true;
		this._toolsScroll.WidgetShouldRender = true;
		this._toolsScroll.LayoutExpandHeight = false;
		this._toolsScroll.LayoutExpandWidth = false;
		this._toolsScroll.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.Layout;
		this._scrollWindow.AddChild(this._toolsScroll);
	
	
		//Property setters for ->_btnPanels
		this._btnPanels.Label = "Panels";
		this._btnPanels.FontSize = 11;
		this._btnPanels.FontStyle = UnityEngine.FontStyle.Normal;
		this._btnPanels.WordWrap = false;
		this._btnPanels.Alignment = UnityEngine.TextAnchor.MiddleCenter;
		this._btnPanels.BaseStyle = "";
		this._btnPanels.Clipping = UnityEngine.TextClipping.Overflow;
		this._btnPanels.Margin.top = 2;
		this._btnPanels.Margin.bottom = 2;
		this._btnPanels.Margin.left = 4;
		this._btnPanels.Margin.right = 4;
		this._btnPanels.Padding.top = 1;
		this._btnPanels.Padding.bottom = 2;
		this._btnPanels.Padding.left = 3;
		this._btnPanels.Padding.right = 3;
		this._btnPanels.Border.top = 4;
		this._btnPanels.Border.bottom = 4;
		this._btnPanels.Border.left = 6;
		this._btnPanels.Border.right = 6;
		this._btnPanels.Height = 20f;
		this._btnPanels.Width = 110f;
		this._btnPanels.Name = "_btnPanels";
		this._btnPanels.PositionX = 1f;
		this._btnPanels.PositionY = 1f;
		this._btnPanels.GUIEnabled = true;
		this._btnPanels.WidgetShouldRender = true;
		this._btnPanels.LayoutExpandHeight = false;
		this._btnPanels.LayoutExpandWidth = false;
		this._btnPanels.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.Layout;
		this._toolsScroll.AddChild(this._btnPanels);
	
	
		//Property setters for ->_vertPanels
		this._vertPanels.BaseStyle = "";
		this._vertPanels.Clipping = UnityEngine.TextClipping.Overflow;
		this._vertPanels.Margin.top = 0;
		this._vertPanels.Margin.bottom = 0;
		this._vertPanels.Margin.left = 5;
		this._vertPanels.Margin.right = 0;
		this._vertPanels.Padding.top = 0;
		this._vertPanels.Padding.bottom = 0;
		this._vertPanels.Padding.left = 0;
		this._vertPanels.Padding.right = 0;
		this._vertPanels.Border.top = 0;
		this._vertPanels.Border.bottom = 0;
		this._vertPanels.Border.left = 0;
		this._vertPanels.Border.right = 0;
		this._vertPanels.Height = -1f;
		this._vertPanels.Width = -1f;
		this._vertPanels.Name = "_vertPanels";
		this._vertPanels.ChildrenShouldRender = true;
		this._vertPanels.PositionX = 1f;
		this._vertPanels.PositionY = 1f;
		this._vertPanels.GUIEnabled = true;
		this._vertPanels.WidgetShouldRender = false;
		this._vertPanels.LayoutExpandHeight = false;
		this._vertPanels.LayoutExpandWidth = false;
		this._vertPanels.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.Layout;
		this._toolsScroll.AddChild(this._vertPanels);
	
	
		//Property setters for ->_btnWidgets
		this._btnWidgets.Label = "Widgets";
		this._btnWidgets.FontSize = 11;
		this._btnWidgets.FontStyle = UnityEngine.FontStyle.Normal;
		this._btnWidgets.WordWrap = false;
		this._btnWidgets.Alignment = UnityEngine.TextAnchor.MiddleCenter;
		this._btnWidgets.BaseStyle = "";
		this._btnWidgets.Clipping = UnityEngine.TextClipping.Overflow;
		this._btnWidgets.Margin.top = 2;
		this._btnWidgets.Margin.bottom = 2;
		this._btnWidgets.Margin.left = 4;
		this._btnWidgets.Margin.right = 4;
		this._btnWidgets.Padding.top = 1;
		this._btnWidgets.Padding.bottom = 2;
		this._btnWidgets.Padding.left = 3;
		this._btnWidgets.Padding.right = 3;
		this._btnWidgets.Border.top = 4;
		this._btnWidgets.Border.bottom = 4;
		this._btnWidgets.Border.left = 6;
		this._btnWidgets.Border.right = 6;
		this._btnWidgets.Height = 20f;
		this._btnWidgets.Width = 110f;
		this._btnWidgets.Name = "_btnWidgets";
		this._btnWidgets.PositionX = 1f;
		this._btnWidgets.PositionY = 1f;
		this._btnWidgets.GUIEnabled = true;
		this._btnWidgets.WidgetShouldRender = true;
		this._btnWidgets.LayoutExpandHeight = false;
		this._btnWidgets.LayoutExpandWidth = false;
		this._btnWidgets.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.Layout;
		this._toolsScroll.AddChild(this._btnWidgets);
	
	
		//Property setters for ->_vertWidgets
		this._vertWidgets.BaseStyle = "";
		this._vertWidgets.Clipping = UnityEngine.TextClipping.Overflow;
		this._vertWidgets.Margin.top = 0;
		this._vertWidgets.Margin.bottom = 0;
		this._vertWidgets.Margin.left = 5;
		this._vertWidgets.Margin.right = 0;
		this._vertWidgets.Padding.top = 0;
		this._vertWidgets.Padding.bottom = 0;
		this._vertWidgets.Padding.left = 0;
		this._vertWidgets.Padding.right = 0;
		this._vertWidgets.Border.top = 0;
		this._vertWidgets.Border.bottom = 0;
		this._vertWidgets.Border.left = 0;
		this._vertWidgets.Border.right = 0;
		this._vertWidgets.Height = -1f;
		this._vertWidgets.Width = -1f;
		this._vertWidgets.Name = "_vertWidgets";
		this._vertWidgets.ChildrenShouldRender = true;
		this._vertWidgets.PositionX = 1f;
		this._vertWidgets.PositionY = 1f;
		this._vertWidgets.GUIEnabled = true;
		this._vertWidgets.WidgetShouldRender = false;
		this._vertWidgets.LayoutExpandHeight = false;
		this._vertWidgets.LayoutExpandWidth = false;
		this._vertWidgets.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.Layout;
		this._toolsScroll.AddChild(this._vertWidgets);
	
	
		//Property setters for ->_btnControls
		this._btnControls.Label = "Controls";
		this._btnControls.FontSize = 11;
		this._btnControls.FontStyle = UnityEngine.FontStyle.Normal;
		this._btnControls.WordWrap = false;
		this._btnControls.Alignment = UnityEngine.TextAnchor.MiddleCenter;
		this._btnControls.BaseStyle = "";
		this._btnControls.Clipping = UnityEngine.TextClipping.Overflow;
		this._btnControls.Margin.top = 2;
		this._btnControls.Margin.bottom = 2;
		this._btnControls.Margin.left = 4;
		this._btnControls.Margin.right = 4;
		this._btnControls.Padding.top = 1;
		this._btnControls.Padding.bottom = 2;
		this._btnControls.Padding.left = 3;
		this._btnControls.Padding.right = 3;
		this._btnControls.Border.top = 4;
		this._btnControls.Border.bottom = 4;
		this._btnControls.Border.left = 6;
		this._btnControls.Border.right = 6;
		this._btnControls.Height = 20f;
		this._btnControls.Width = 110f;
		this._btnControls.Name = "_btnControls";
		this._btnControls.PositionX = 1f;
		this._btnControls.PositionY = 1f;
		this._btnControls.GUIEnabled = true;
		this._btnControls.WidgetShouldRender = true;
		this._btnControls.LayoutExpandHeight = false;
		this._btnControls.LayoutExpandWidth = false;
		this._btnControls.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.Layout;
		this._toolsScroll.AddChild(this._btnControls);
	
	
		//Property setters for ->_vertControls
		this._vertControls.BaseStyle = "";
		this._vertControls.Clipping = UnityEngine.TextClipping.Overflow;
		this._vertControls.Margin.top = 0;
		this._vertControls.Margin.bottom = 0;
		this._vertControls.Margin.left = 5;
		this._vertControls.Margin.right = 0;
		this._vertControls.Padding.top = 0;
		this._vertControls.Padding.bottom = 0;
		this._vertControls.Padding.left = 0;
		this._vertControls.Padding.right = 0;
		this._vertControls.Border.top = 0;
		this._vertControls.Border.bottom = 0;
		this._vertControls.Border.left = 0;
		this._vertControls.Border.right = 0;
		this._vertControls.Height = -1f;
		this._vertControls.Width = -1f;
		this._vertControls.Name = "_vertControls";
		this._vertControls.ChildrenShouldRender = true;
		this._vertControls.PositionX = 1f;
		this._vertControls.PositionY = 1f;
		this._vertControls.GUIEnabled = true;
		this._vertControls.WidgetShouldRender = false;
		this._vertControls.LayoutExpandHeight = false;
		this._vertControls.LayoutExpandWidth = false;
		this._vertControls.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.Layout;
		this._toolsScroll.AddChild(this._vertControls);
	
	
		//Property setters for ->_btnDecorators
		this._btnDecorators.Label = "Decorators";
		this._btnDecorators.FontSize = 11;
		this._btnDecorators.FontStyle = UnityEngine.FontStyle.Normal;
		this._btnDecorators.WordWrap = false;
		this._btnDecorators.Alignment = UnityEngine.TextAnchor.MiddleCenter;
		this._btnDecorators.BaseStyle = "";
		this._btnDecorators.Clipping = UnityEngine.TextClipping.Overflow;
		this._btnDecorators.Margin.top = 2;
		this._btnDecorators.Margin.bottom = 2;
		this._btnDecorators.Margin.left = 4;
		this._btnDecorators.Margin.right = 4;
		this._btnDecorators.Padding.top = 1;
		this._btnDecorators.Padding.bottom = 2;
		this._btnDecorators.Padding.left = 3;
		this._btnDecorators.Padding.right = 3;
		this._btnDecorators.Border.top = 4;
		this._btnDecorators.Border.bottom = 4;
		this._btnDecorators.Border.left = 6;
		this._btnDecorators.Border.right = 6;
		this._btnDecorators.Height = 20f;
		this._btnDecorators.Width = 110f;
		this._btnDecorators.Name = "_btnDecorators";
		this._btnDecorators.PositionX = 1f;
		this._btnDecorators.PositionY = 1f;
		this._btnDecorators.GUIEnabled = true;
		this._btnDecorators.WidgetShouldRender = true;
		this._btnDecorators.LayoutExpandHeight = false;
		this._btnDecorators.LayoutExpandWidth = false;
		this._btnDecorators.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.Layout;
		this._toolsScroll.AddChild(this._btnDecorators);
	
	
		//Property setters for ->_vertDecorators
		this._vertDecorators.BaseStyle = "";
		this._vertDecorators.Clipping = UnityEngine.TextClipping.Overflow;
		this._vertDecorators.Margin.top = 0;
		this._vertDecorators.Margin.bottom = 0;
		this._vertDecorators.Margin.left = 5;
		this._vertDecorators.Margin.right = 0;
		this._vertDecorators.Padding.top = 0;
		this._vertDecorators.Padding.bottom = 0;
		this._vertDecorators.Padding.left = 0;
		this._vertDecorators.Padding.right = 0;
		this._vertDecorators.Border.top = 0;
		this._vertDecorators.Border.bottom = 0;
		this._vertDecorators.Border.left = 0;
		this._vertDecorators.Border.right = 0;
		this._vertDecorators.Height = -1f;
		this._vertDecorators.Width = -1f;
		this._vertDecorators.Name = "_vertDecorators";
		this._vertDecorators.ChildrenShouldRender = true;
		this._vertDecorators.PositionX = 1f;
		this._vertDecorators.PositionY = 1f;
		this._vertDecorators.GUIEnabled = true;
		this._vertDecorators.WidgetShouldRender = false;
		this._vertDecorators.LayoutExpandHeight = false;
		this._vertDecorators.LayoutExpandWidth = false;
		this._vertDecorators.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.Layout;
		this._toolsScroll.AddChild(this._vertDecorators);
	
	
		//Property setters for ->_btnOthers
		this._btnOthers.Label = "Others";
		this._btnOthers.FontSize = 11;
		this._btnOthers.FontStyle = UnityEngine.FontStyle.Normal;
		this._btnOthers.WordWrap = false;
		this._btnOthers.Alignment = UnityEngine.TextAnchor.MiddleCenter;
		this._btnOthers.BaseStyle = "";
		this._btnOthers.Clipping = UnityEngine.TextClipping.Overflow;
		this._btnOthers.Margin.top = 2;
		this._btnOthers.Margin.bottom = 2;
		this._btnOthers.Margin.left = 4;
		this._btnOthers.Margin.right = 4;
		this._btnOthers.Padding.top = 1;
		this._btnOthers.Padding.bottom = 2;
		this._btnOthers.Padding.left = 3;
		this._btnOthers.Padding.right = 3;
		this._btnOthers.Border.top = 4;
		this._btnOthers.Border.bottom = 4;
		this._btnOthers.Border.left = 6;
		this._btnOthers.Border.right = 6;
		this._btnOthers.Height = 20f;
		this._btnOthers.Width = 110f;
		this._btnOthers.Name = "_btnOthers";
		this._btnOthers.PositionX = 1f;
		this._btnOthers.PositionY = 1f;
		this._btnOthers.GUIEnabled = true;
		this._btnOthers.WidgetShouldRender = true;
		this._btnOthers.LayoutExpandHeight = false;
		this._btnOthers.LayoutExpandWidth = false;
		this._btnOthers.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.Layout;
		this._toolsScroll.AddChild(this._btnOthers);
	
	
		//Property setters for ->_vertOthers
		this._vertOthers.BaseStyle = "";
		this._vertOthers.Clipping = UnityEngine.TextClipping.Overflow;
		this._vertOthers.Margin.top = 0;
		this._vertOthers.Margin.bottom = 0;
		this._vertOthers.Margin.left = 5;
		this._vertOthers.Margin.right = 0;
		this._vertOthers.Padding.top = 0;
		this._vertOthers.Padding.bottom = 0;
		this._vertOthers.Padding.left = 0;
		this._vertOthers.Padding.right = 0;
		this._vertOthers.Border.top = 0;
		this._vertOthers.Border.bottom = 0;
		this._vertOthers.Border.left = 0;
		this._vertOthers.Border.right = 0;
		this._vertOthers.Height = -1f;
		this._vertOthers.Width = -1f;
		this._vertOthers.Name = "_vertOthers";
		this._vertOthers.ChildrenShouldRender = true;
		this._vertOthers.PositionX = 1f;
		this._vertOthers.PositionY = 1f;
		this._vertOthers.GUIEnabled = true;
		this._vertOthers.WidgetShouldRender = false;
		this._vertOthers.LayoutExpandHeight = false;
		this._vertOthers.LayoutExpandWidth = false;
		this._vertOthers.LayoutMode = uAssist.UEditorWidgets.ePositioningLayout.Layout;
		this._toolsScroll.AddChild(this._vertOthers);
	
	


        }

    }
}